#
#
version: '3'

networks:
  dev-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.0.0.0/24

services:
  kiva-tools-dotnet-env:
    build: ./
    command: bash
    image: kiva-tools-dotnet-env
    container_name: kiva-tools-dotnet-env
    working_dir: /src
    volumes:
     - ./:/src
    networks:
      - dev-network
    tty: true

volumes:
  node_modules:
  db_data: {}
