#
#
version: '3'

networks:
  kiva-network:
    external: true

services:
  kiva-tools-besu-env:
    build: ./
    command: bash
    image: kiva-tools-besu-env
    container_name: kiva-tools-besu-env
    working_dir: /besu
    volumes:
     - ./keep:/besu/keep
     - ./ignore:/besu/ignore
    ports:
      - 8545:8545     # JSON-RPC over HTTP
      - 8546:8546     # JSON-RPC over WebSockets
      - 8547:8547     # GraphQL over HTTP
      - 30303:30303   # P2P port
    expose:
      - "8545"
      - "8546"
      - "8547"
      - "30303"
    env_file:
      - ./keep/.bootnode_env
    networks:
      - kiva-network
    tty: true

volumes:
  node_modules:
  db_data: {}
