#
#
version: '3'

networks:
  dev-network:
    external: true

services:
  kiva-tools-rust-env:
    build: ./
    command: bash
    image: kiva-tools-rust-env
    container_name: kiva-tools-rust-env
    environment:
      - PATH="~/.cargo/bin:${PATH}"
    working_dir: /src
    volumes:
     - ./:/src
     - node_modules:/www/node_modules
    networks:
      - dev-network
    tty: true

volumes:
  node_modules:
  db_data: {}
